name: peviitor.ro
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run jmeter on github action
        uses: sebiboga/run-jmeter-github-action@v0.0.3
